[package]
name = "new_proxy"
version = "5.0.0"
edition = "2021"

[[bin]]
name = "new_proxy"
path = "src/main.rs"
test = false

[dependencies]
quinn-proto = "0.10"
rustls = { version = "0.21", features = ["quic", "dangerous_configuration"] }
bytes = "1.5"
libc = "0.2"
ipnet = "2.9"
rand = "0.8"
log = "0.4"
env_logger = "0.10"
hmac = "0.12"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }

[dev-dependencies]
rcgen = "0.11"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = true
