[Interface]
PrivateKey = etewwnbYf1Zk8wnouPD/qbVWQpP9xW61CeNZ4JCXo24=
Address = 10.0.0.2/24, fd00::2/64
TProxyPort = 1080
MTU = 1400

[Peer]
PublicKey = vWwaq2WH6+bOvcsFJHRqOhvMoPxBMHkWrug2YfyQ3ho=
Endpoint = 10.0.2.2:51820
ProxyPort = 51821
AllowedIPs = 10.0.0.1/32, fd00::1/128
